server:
  port: 7777
robot:
  ip: xxx:3001
spring:
  datasource:
    url: jdbc:mysql://xxx:3306/httpqqrobot?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: HttpQQrobot
  redis:
    host: xxx
    port: 6379
    database: 0
    timeout: 1800000
    password: xxx
nacos:
  config:
    server-addr: xxx:8848
    namespace: dev
mybatis-plus:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*Mapper.xml
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  keepAliveTime: 60
  blockingQueueSize: 20
rocketmq:
  name-server: xxx:9876
  producer:
    group: httpqqrobot-producer-group