server:
  port: 7777
robot:
  configPath: D:\MyProject\HttpQQrobot-master\go-cqhttp\config.yml
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/httpqqrobot?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: HttpQQrobot
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: dev
mybatis-plus:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*Mapper.xml
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  keepAliveTime: 60
  blockingQueueSize: 20
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: httpqqrobot-producer-group