server:
  port: 7777
robot:
  ip: xxxx:3000
spring:
  datasource:
    url: jdbc:mysql://xxxx:3306/httpqqrobot?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxxx
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: HttpQQrobot
  redis:
    host: xxxx
    port: 6379
    database: 0
    timeout: 1800000
    password: xxxx
nacos:
  config:
    serverAddr: xxxx:8848
    namespace: dev
    group: DEFAULT_GROUP
    excludeWordsDataId: excludeWords-dev.properties
    readConfigTimeout: 5000
mybatis-plus:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*Mapper.xml
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  keepAliveTime: 60
  blockingQueueSize: 20